"""
nextflow_config.py  --  generate the nextflow.config for the head instance.

The config is rendered at runtime so we can inject:
  - queueSize  (derived from truffle quota query)
  - workDir    (s3://bucket/work/job-name/)
  - region     (from config.py)
  - AMI ID     (from config.py, pre-baked with databases)
  - S3 bucket  (for progress trace file)
"""

from __future__ import annotations

# nf-core/taxprofiler process labels → instance types.
# Sized for the actual workload:
#   process_low:    fastp, FastQC, MultiQC — light CPU, minimal RAM
#   process_medium: MetaPhlAn 4 — moderate RAM (marker database ~3 GB)
#   process_high:   Kraken2 — needs 32 GB RAM to hold k2_pluspf in memory
#   process_single: fasterq-dump — I/O bound, single-core, cheap instance
_LABEL_INSTANCE_TYPES: dict[str, str] = {
    "process_single": "t4g.medium",  # fasterq-dump, SRA conversion
    "process_low": "t4g.large",  # fastp, FastQC, MultiQC
    "process_medium": "c7g.2xlarge",  # MetaPhlAn 4
    "process_high": "c7g.4xlarge",  # Kraken2 (needs 32 GB RAM)
}

# All instance types in use — passed to truffle.derive_queue_size().
ALL_INSTANCE_TYPES: list[str] = list(set(_LABEL_INSTANCE_TYPES.values()))

_TEMPLATE = """\
// nextflow.config — generated by aws-microbiome-demo
// DO NOT EDIT: regenerated on each run with live quota data

plugins {{
    id 'nf-spawn@0.1.0'
}}

process {{
    executor = 'spawn'

    // Per-label instance types — sized for the actual workload.
    withLabel: 'process_single' {{ ext.instanceType = '{inst_single}' }}
    withLabel: 'process_low'    {{ ext.instanceType = '{inst_low}'    }}
    withLabel: 'process_medium' {{ ext.instanceType = '{inst_medium}' }}
    withLabel: 'process_high'   {{ ext.instanceType = '{inst_high}'   }}

    // Fallback for unlabelled processes.
    ext.instanceType = '{inst_low}'
    ext.region       = '{region}'
    ext.ttl          = '2h'
    ext.ami          = '{ami_id}'
}}

executor {{
    name      = 'spawn'
    queueSize = {queue_size}    // derived from truffle quota query
}}

params {{
    // Classifier databases (pre-staged on the AMI).
    kraken2_db   = '/opt/databases/kraken2'
    metaphlan_db = '/opt/databases/metaphlan'

    // Pipeline flags.
    run_kraken2                      = true
    run_metaphlan                    = true
    run_bracken                      = false
    run_humann                       = false
    perform_shortread_hostremoval    = false
    shortread_qc_tool                = 'fastp'
    save_preprocessed_reads          = false
}}

// S3 work directory — intermediate files pass between instances via S3.
// Each task downloads its inputs, runs, uploads outputs, terminates.
workDir = 's3://{bucket}/work/{job_name}/'

// Publish final results to a separate prefix (not the ephemeral work dir).
params.outdir = 's3://{bucket}/results/{job_name}/'

// Post-process hook: after each KRAKEN2_CLASSIFY task completes, convert the
// Kraken2 report to the JSON format that pipeline._sample_species() reads.
// The script runs on the task instance before it terminates.
process.afterScript = '''
if [ -f "*.report.txt" ]; then
  python3 - << 'PYEOF'
import glob, json, os, re, boto3

bucket   = os.environ.get("NXF_WORK_BUCKET", "").lstrip("s3://").split("/")[0]
job_name = os.environ.get("NXF_JOB_NAME", "microbiome-demo")

def parse_report(path):
    species = []
    with open(path) as f:
        for line in f:
            fields = line.strip().split("\\t")
            if len(fields) >= 6 and fields[3] == "S" and float(fields[0]) > 0.1:
                species.append({"name": fields[5].strip(),
                                "pct":   float(fields[0]),
                                "reads": int(fields[1])})
    return sorted(species, key=lambda x: x["pct"], reverse=True)

for report in glob.glob("*.report.txt"):
    m = re.search(r"(SRR\\d+)", report)
    if not m or not bucket:
        continue
    srr = m.group(1)
    # Body site is encoded in the sample name passed by Nextflow
    body_site = os.environ.get("NXF_TASK_NAME", "unknown").split("_", 1)[-1]
    data = {"srr": srr, "body_site": body_site,
            "top_species": [s["name"] for s in parse_report(report)[:10]],
            "species_detail": parse_report(report)[:20]}
    boto3.client("s3").put_object(
        Bucket=bucket,
        Key=f"results/{job_name}/kraken2/{srr}.json",
        Body=json.dumps(data)
    )
PYEOF
fi
'''

// Trace file written to S3 — the dashboard polls this for live progress.
trace {{
    enabled   = true
    file      = 's3://{bucket}/results/{job_name}/trace.tsv'
    overwrite = true
    fields    = 'task_id,name,status,exit,start,complete,duration,realtime,cpus,memory,rss,vmem,rchar,wchar'
}}

// Capture RODA reads and FASTQ sizes in the timeline for data-volume reporting.
timeline {{
    enabled = true
    file    = 's3://{bucket}/results/{job_name}/timeline.html'
}}

report {{
    enabled = true
    file    = 's3://{bucket}/results/{job_name}/report.html'
}}
"""


def render(cfg, queue_size: int) -> str:
    """Return a nextflow.config string with all values substituted.

    Args:
        cfg:        config module (REGION, BUCKET, JOB_NAME, AMI_ID).
        queue_size: derived from truffle.derive_queue_size().
    """
    return _TEMPLATE.format(
        region=cfg.REGION,
        bucket=cfg.BUCKET,
        job_name=cfg.JOB_NAME,
        ami_id=cfg.AMI_ID,
        queue_size=queue_size,
        inst_single=_LABEL_INSTANCE_TYPES["process_single"],
        inst_low=_LABEL_INSTANCE_TYPES["process_low"],
        inst_medium=_LABEL_INSTANCE_TYPES["process_medium"],
        inst_high=_LABEL_INSTANCE_TYPES["process_high"],
    )
